[book]
authors = ["oJa6aN"]
language = "en"
multilingual = false
src = "src"
title = "VALORANT Guide"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-css = ["custom.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
